catalog
htmlacademy-htmlcss/1913295-sedona-32 pull request #6
Opened 2021-11-03 19:45 UTC by Dmitrii129

2021-11-03 19:45 UTC, Dmitrii129 commented
кнопка "показать еще" не получается

2021-11-04 13:42 UTC, Pakistanka requested changes
1. Нужно поправить ошибки, которые показывает валидатор - http://joxi.ru/V2V7Mg0u8ooQWA
Ссылка на валидатор - https://validator.w3.org/nu/#textarea

2021-11-04 13:42 UTC, Pakistanka commented on catalog.html
> +</head>
Прорешать ошибки валидатора - http://joxi.ru/Q2KZXBktyllPbm
Вот ссылка на валидтор - https://validator.w3.org/nu/#textarea

2021-11-04 13:42 UTC, Pakistanka commented on catalog.html
> +  <main class="main-inner">
Стили для main

`width: 1200px;
    overflow-x: hidden;`

2021-11-04 13:42 UTC, Pakistanka commented on style/style.css
> +  margin-left: 650px;
Удалить эту строку!!!!

2021-11-04 13:42 UTC, Pakistanka commented on style/style.css
> +.catalog-block1 {
.catalog-block1, .catalog-block2, .catalog-block3, .catalog-block4 - однотипные блоки! Ты можешь им дать одинаковое имя класс .catalog-block и вызывать в css 1 раз

2021-11-04 13:42 UTC, Pakistanka commented on style/style.css
> +  height: 384px;
Убрать или заменить на min-height. Высота должна формироваться динамически за счет отступов и контента

2021-11-04 13:42 UTC, Pakistanka commented on style/style.css
> +  height: 282px;
Убрать. Высота должна формироваться динамически за счет отступов и контента

2021-11-04 13:42 UTC, Pakistanka commented on style/style.css
> +  height: 384px;
Убрать или заменить на min-height. Высота должна формироваться динамически за счет отступов и контента

2021-11-04 13:42 UTC, Pakistanka commented on style/style.css
> +  height: 411px;
Убрать или заменить на min-height. Высота должна формироваться динамически за счет отступов и контента

2021-11-04 13:42 UTC, Pakistanka commented on style/style.css
> +  height: 408px;
Убрать или заменить на min-height. Высота должна формироваться динамически за счет отступов и контента

2021-11-04 13:42 UTC, Pakistanka commented on style/style.css
> +  margin-left: 250px;
Слишком большой margin, нужно что-то другое

2021-11-04 13:42 UTC, Pakistanka commented on style/style.css
> +  padding-left: -150px;
Нельзя! Убрать! Ищи другое решение

2021-11-04 13:42 UTC, Pakistanka commented on style/style.css
> +  height: 411px;
Убрать или заменить на min-height. Высота должна формироваться динамически за счет отступов и контента

2021-11-06 11:55 UTC, merged